### ISSUE TITLE
Files crv_item_data.json acrv_item_data_base.json and measured_weights.json location

### ISSUE THREAD

**Issue by aitorgutierrez** [warehouse-picking-automation-challenges/team_acrv_2017#1]
Hi!

Where are located acrv_item_data.json acrv_item_data_base.json and measured_weights.json?

Do you explain somewhere how you train the model?

Thanks

**Comment by dougsm** [comment]
Hello,
The files you mentioned are in this directory:
[https://github.com/warehouse-picking-automation-challenges/team_acrv_2017/tree/master/apc_state_machine/state_machine/data](https://github.com/warehouse-picking-automation-challenges/team_acrv_2017/tree/master/apc_state_machine/state_machine/data)

For info on training the network, have a look at:
[https://github.com/warehouse-picking-automation-challenges/team_acrv_2017/tree/master/acrv_apc_2017_perception/src/refinenet](https://github.com/warehouse-picking-automation-challenges/team_acrv_2017/tree/master/acrv_apc_2017_perception/src/refinenet)  (the README and train.py)
and
[https://github.com/warehouse-picking-automation-challenges/team_acrv_2017/blob/master/instructions/train_data.md](https://github.com/warehouse-picking-automation-challenges/team_acrv_2017/blob/master/instructions/train_data.md)
